title: Pollawat Hongwimol # your name (or website title) here
logo: "/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br><br> elements if you don't need line breaks)

<h1> adsfadf </h1>

theme: jekyll-theme-minimal
google_analytics: UA-146164975-1 # your Google Analytics tracking ID here

#show_downloads: true
